on: [push]

name: build


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check system
        run: |
          lscpu && free -h

      - name: Start redpanda
        run: |
          bash scripts/redpanda/start.sh

      - name: Setup zig
        run: |
          bash src/zig/setup.sh

      - name: Run python
        run: |
          bash src/python/run.sh
