on: [push]

name: build

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: check system
        run: |
          lscpu && free -h

      - name: Start redpanda
        run: |
          bash scripts/redpanda/start.sh

      - name: Run python
        run: |
          bash src/python/run.sh

      - name: Setup and run c
        run: |
          bash src/c/setup.sh
          bash src/c/run_example.sh