on: [push]

name: build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: check system
        run: |
          lscpu && free -h

      - name: Start redpanda
        timeout-minutes: 5
        run: |
          bash scripts/redpanda/start.sh

      - name: Run python
        timeout-minutes: 5
        run: |
          bash src/python/run.sh

      - name: Setup and run c
        timeout-minutes: 5
        run: |
          bash src/c/setup.sh
          bash src/c/run_example.sh


  setup-zig:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: check system
        run: |
          lscpu && free -h

      - name: Setup zig
        timeout-minutes: 5
        run: |
          bash src/zig/setup.sh

  